
[[animation]]
name = "_Attack"
speed = 150
columns = 4
rows = 1

[[animation]]
name = "_Attack2"
speed = 150
columns = 6
rows = 1

[[animation]]
name = "_Attack2NoMovement"
speed = 150
columns = 6
rows = 1

[[animation]]
name = "_AttackCombo"
speed = 150
columns = 10
rows = 1

[[animation]]
name = "_AttackComboNoMovement"
speed = 150
columns = 10
rows = 1

[[animation]]
name = "_AttackNoMovement"
speed = 350
columns = 4
rows = 1

[[animation]]
name = "_Crouch"
speed = 150
columns = 1
rows = 1

[[animation]]
name = "_CrouchAll"
speed = 150
columns = 3
rows = 1

[[animation]]
name = "_CrouchAttack"
speed = 100
columns = 4
rows = 1

[[animation]]
name = "_CrouchTransition"
speed = 150
columns = 1
rows = 1

[[animation]]
name = "_CrouchWalk"
speed = 150
columns = 8
rows = 1

[[animation]]
name = "_Dash"
speed = 150
columns = 2
rows = 1

[[animation]]
name = "_Death"
speed = 150
columns = 10
rows = 1

[[animation]]
name = "_DeathNoMovement"
speed = 150
columns = 10
rows = 1

[[animation]]
name = "_Fall"
speed = 150
columns = 3
rows = 1

[[animation]]
name = "_Hit"
speed = 150
columns = 1
rows = 1

[[animation]]
name = "_Idle"
speed = 300
columns = 10
rows = 1

[[animation]]
name = "_Jump"
speed = 150
columns = 3
rows = 1

[[animation]]
name = "_JumpFallInbetween"
speed = 150
columns = 2
rows = 1

[[animation]]
name = " _Roll"
speed = 150
columns = 12
rows = 1

[[animation]]
name = "_Run"
speed = 100
columns = 10
rows = 1

[[animation]]
name = "_Slide"
speed = 150
columns = 2
rows = 1

[[animation]]
name = "_SlideAll"
speed = 150
columns = 4
rows = 1

[[animation]]
name = "_SlideTransitionEnd"
speed = 150
columns = 1
rows = 1

[[animation]]
name = "_SlideTransitionStart"
speed = 150
columns = 1
rows = 1

[[animation]]
name = "_TurnAround"
speed = 150
columns = 3
rows = 1

[[animation]]
name = "_WallClimb"
speed = 150
columns = 7
rows = 1

[[animation]]
name = "_WallClimbNoMovement"
speed = 150
columns = 7
rows = 1

[[animation]]
name = "_WallHang"
speed = 150
columns = 1
rows = 1

[[animation]]
name = "_WallSlide"
speed = 150
columns = 3
rows = 1
